"use client";
import { useEffect, useState } from "react";
type Assignment = { id: number; class_code: string; title: string; description: string; subject: string; deadline_at: string; max_score: number; status: string; submission_status: string | null; score: number | null; feedback: string | null };
export default function StudentAssignmentsPage() {
    const [items, setItems] = useState<Assignment[]>([]); const [message, setMessage] = useState(""); const [uploading, setUploading] = useState(0);
    async function load() { const r = await fetch("/api/enrollment/assignments"); const d = await r.json(); setMessage(r.ok ? "" : d.error); if (r.ok) setItems(d.data ?? []); }
    useEffect(() => { void load(); }, []);
    async function upload(id: number, file?: File) { if (!file) return; setUploading(id); const form = new FormData(); form.append("file", file); const r = await fetch(`/api/enrollment/assignments/${id}/submissions`, { method: "POST", body: form }); const d = await r.json(); setUploading(0); setMessage(d.error || d.message); if (r.ok) await load(); }
    return <div className="mx-auto max-w-5xl space-y-6 px-4 py-8"><header className="rounded-[1.75rem] bg-primary-80 p-7 text-white"><h1 className="text-3xl font-black">Tugas Saya</h1></header>{message && <div className="rounded-xl bg-primary-10 p-4 text-primary-base">{message}</div>}{items.length === 0 ? <div className="portal-card p-10 text-center">Belum ada tugas.</div> : items.map((a) => <article key={a.id} className="portal-card p-6"><div className="flex justify-between gap-5"><div><p className="text-xs font-bold text-primary-base">{a.class_code} · {a.subject}</p><h2 className="text-xl font-black">{a.title}</h2><p className="mt-3 text-sm text-neutral-60">{a.description}</p><p className="mt-3 text-sm font-semibold">Deadline {new Date(a.deadline_at).toLocaleString("id-ID", { timeZone: "Asia/Jakarta" })}</p><p className="mt-2 text-sm">Status: {a.submission_status || "Belum mengumpulkan"}</p>{a.score !== null && <div className="mt-3 rounded-xl bg-success-10 p-3"><b>Nilai {a.score}/{a.max_score}</b><p>{a.feedback}</p></div>}</div>{a.status === "published" && a.score === null && <label className="h-fit cursor-pointer rounded-xl bg-primary-base px-4 py-3 text-sm font-bold text-white">{uploading === a.id ? "Mengunggah..." : "Unggah PDF"}<input className="sr-only" type="file" accept=".pdf,application/pdf" onChange={(e) => { void upload(a.id, e.target.files?.[0]); e.target.value = ""; }} /></label>}</div></article>)}</div>;
}
