export {
    connectMySQL,
    queryMySQL,
    getConnection,
    closeMySQLConnection,
    type Pool,
    type PoolConnection,
    type RowDataPacket,
    type ResultSetHeader,
} from "./mysql-connection";

export {
    ensureQuizTables,
    isValidNumericId,
    findStudentById,
    findStudentByEmail,
    createStudent,
    resetStudentForRetry,
    completeStudentRegistration,
    updateStudentPaymentProof,
    ensureStudentTestStarted,
    findQuestionById,
    findRandomUnansweredQuestion,
    addStudentAnswer,
    finishStudentTest,
    replaceQuestions,
    type QuizStudent,
    type QuizQuestion,
    type QuizAnswer,
    type QuizLevel,
} from "./quiz-mysql";

export {
    ensureNewsInfrastructure,
    syncNewsFromWordPress,
    listNews,
    listNewsSummary,
    findNewsBySlug,
    type NewsItem,
    type NewsItemSummary,
} from "./news-mysql";

export {
    ensureDailyQuizTables,
    replaceDailyQuizQuestions,
    listDailyQuizQuestions,
    getDailyQuizQuestionCount,
    getDailyQuizQuestionsForDate,
    submitDailyQuizAttempt,
    findLatestDailyQuizAttempt,
    findTodayDailyQuizAttempt,
    getDailyQuizAttemptLeaderboard,
    type DailyQuizQuestion,
    type DailyQuizQuestionSeed,
    type DailyQuizAttempt,
    type DailyQuizLeaderboardItem,
} from "./daily-quiz-mysql";

export {
    ensureGalleryTable,
    listGalleryItems,
    findGalleryItemById,
    createGalleryItem,
    updateGalleryItem,
    deleteGalleryItem,
    type GalleryItem,
} from "./gallery-mysql";

export {
    ensureMerchandiseTable,
    listMerchandiseItems,
    findMerchandiseItemById,
    createMerchandiseItem,
    updateMerchandiseItem,
    deleteMerchandiseItem,
    type MerchandiseItem,
} from "./merchandise-mysql";

export {
    createCounselingRegistration,
    listCounselingRegistrations,
    VALID_EDUCATION_LEVELS,
    VALID_TOPICS,
    type CounselingRegistration,
    type CreateCounselingInput,
    type ListCounselingOptions,
    type ListCounselingResult,
    type EducationLevel,
    type CounselingTopic,
} from "./counseling-mysql";

export {
    ensureLmsTables,
    listCourses,
    findCourseById,
    createCourse,
    updateCourse,
    deleteCourse,
    findEnrollmentsByStudent,
    enrollStudent,
    updateEnrollmentStatus,
    findLessonsByCourse,
    findLessonById,
    createLesson,
    updateLesson,
    deleteLesson,
    findProgressByStudentAndCourse,
    markLessonComplete,
    submitQuizGrade,
    findLatestQuizGrade,
    getStudentDashboard,
    findCoursesByTeacher,
    type CourseLevel,
    type EnrollmentStatus,
    type LessonContentType,
    type LmsCourse,
    type LmsEnrollment,
    type LmsLesson,
    type LmsLessonProgress,
    type LmsQuizGrade,
    type StudentDashboard,
} from "./lms-mysql";

export {
    ensureEnrollmentTables,
    createPortalClass,
    findPortalClass,
    listPortalClasses,
    updatePortalClass,
    transitionPortalClass,
    resolvePreStudentId,
    submitApplication,
    listCandidateApplications,
    withdrawApplication,
    listApplications,
    reviewApplication,
    rejectApplication,
    acceptApplication,
    listClassMembers,
    listClassTeachers,
    assignClassTeacher,
    removeClassTeacher,
    listAvailableTeachers,
    type PortalClassInput,
    type PortalClassStatus,
    type ApplicationStatus,
} from "./enrollment-mysql";

export {
    ensureAssignmentTables,
    teacherCanManageClass,
    studentHasActiveMembership,
    createAssignment,
    publishAssignment,
    closeAssignment,
    findAssignment,
    listAssignmentsForTeacher,
    listAssignmentsForStudent,
    recordSubmission,
    listAssignmentSubmissions,
    gradeSubmission,
    getAcademicReport,
    processNotificationOutbox,
    listNotifications,
} from "./assignment-mysql";
